Feature/14 welcome screen guest UI
BrightCoders-Proyectos/tribo-mobile pull request #26
Opened 2020-12-17 22:24 UTC by develiasdaniel

# Description
this is related issue #14 
What did you implemented/Why did you implemented this:
 - design the guest welcome screen
 - reuse components of welcome screen
 - added texts to the constants file
 
Examples:
 - What?: I have added the guest welcome screen, It included design and reuse small components such as the logo, title and description.
 - Why?: this screen will be one of the first that the user sees when they log in

 # Testing
- clone repository
- `npm install`
- `npm react native run-android` or `npm react-native run-ios`
 
 Example:
  - I've added coverage for testing all new methods. I used Faker for a few random user emails and names.
  
  ## Screenshots 
- Guest Welcome Screen
![GuestwelcomeScreen](https://user-images.githubusercontent.com/69357302/102550743-f299ef00-4083-11eb-8fb3-2dc5c92dab35.jpg)

2020-12-17 22:35 UTC, oswaldotovar32 approved these changes, later dismissed

2020-12-17 23:07 UTC, 1ng-HeberH approved these changes, later dismissed

2020-12-21 18:23 UTC, Ocosmee approved these changes, later dismissed

2020-12-21 19:09 UTC, JordiGN approved these changes, later dismissed
Great work, clean as the other one! cool

2020-12-22 00:15 UTC, LeyaimMagma requested changes

2020-12-22 00:15 UTC, LeyaimMagma commented on tribomobile/components/modals/ModalInfoStore.js
> +              </View>
Remove the blanks paces

2020-12-22 00:15 UTC, LeyaimMagma commented
Resolve Conflicting files

2020-12-22 03:57 UTC, develiasdaniel commented on tribomobile/components/modals/ModalInfoStore.js
> +              </View>
Done

2020-12-22 16:01 UTC, JordiGN approved these changes, later dismissed

2020-12-22 16:11 UTC, 1ng-HeberH submitted a review, later dismissed

2020-12-22 16:12 UTC, 1ng-HeberH commented
Well done Dany!!

2020-12-23 17:19 UTC, JordiGN submitted a review, later dismissed

2020-12-23 17:21 UTC, Ocosmee approved these changes, later dismissed

2020-12-23 17:36 UTC, 1ng-HeberH approved these changes, later dismissed

2020-12-23 17:48 UTC, oswaldotovar32 approved these changes, later dismissed

2021-01-04 15:09 UTC, JordiGN approved these changes

2021-01-04 18:05 UTC, 1ng-HeberH approved these changes

2021-01-04 19:03 UTC, LeyaimMagma approved these changes

2021-01-04 19:07 UTC, merged