Feature/33 modify script colors
BrightCoders-Proyectos/tribo-mobile pull request #37
Opened 2021-01-07 18:00 UTC by alcamk

# Description
This feature is related to #33 
 This file only contains the naming convention and the hexadecimal text for the colors 
 Examples:
N/A
 
 # Testing
N/A 
  
  ## Screenshots 
N/A

2021-01-07 18:14 UTC, fernandoamz requested changes

2021-01-07 18:14 UTC, fernandoamz commented on tribomobile/__tests__/App-test.js
>   */
```suggestion

```

2021-01-07 18:14 UTC, fernandoamz commented on tribomobile/__tests__/App-test.js
> +        style={{width: 50, height: 50, backgroundColor: colors.GreenContent}}
The inline styles are not recommended. Could you move the lines where you use inline styles to the stylesheets object?

2021-01-07 18:14 UTC, fernandoamz commented on tribomobile/components/modals/LittlePinInfo.js
> +    color: '#828282',
Standardize the colors on the themes file into shared components and call it here.

2021-01-08 18:16 UTC, 1ng-HeberH submitted a review, later dismissed

2021-01-09 03:08 UTC, develiasdaniel approved these changes, later dismissed
review the comments of mentor
Good job

2021-01-11 17:18 UTC, Ocosmee approved these changes, later dismissed

2021-01-11 17:33 UTC, oswaldotovar32 submitted a review, later dismissed
Nice

2021-01-11 17:43 UTC, 1ng-HeberH commented
Well done Oscar!

2021-01-11 22:22 UTC, LeyaimMagma requested changes
This PR has conflicts

2021-01-11 22:22 UTC, LeyaimMagma commented on tribomobile/screens/registrationScreen.js
> +            </View>
Can you refactor this?

2021-01-11 22:55 UTC, LeyaimMagma approved these changes

2021-01-11 23:47 UTC, JordiGN approved these changes

2021-01-12 00:22 UTC, oswaldotovar32 approved these changes

2021-01-12 17:18 UTC, Ocosmee approved these changes

2021-01-12 17:29 UTC, merged