Creation and design of checkboxs components
BrightCoders-Proyectos/tribo-mobile pull request #46
Opened 2021-01-13 23:28 UTC by Ocosmee

# Description
 - Creation and design of checkbox components from issue #39 
 
 # Testing
- Run npm install
- Run npx react-native start
- Run npx react-native run-android
 
  ## Screenshots 
![Screen](https://user-images.githubusercontent.com/59522204/104522778-13daf600-55c4-11eb-8845-68153330fe87.jpeg)

2021-01-14 00:02 UTC, JordiGN approved these changes, later dismissed
Nice! I'm glad you could solve the issues with the branches

2021-01-14 00:07 UTC, develiasdaniel commented on tribomobile/App.js
> +        <Text style={{marginLeft:35, marginBottom:10, marginTop:10}}>{titlesText.titleRegistrationFormasPago}</Text>
i would recommend put this into style sheet

2021-01-14 00:08 UTC, develiasdaniel submitted a review, later dismissed
Nice job

2021-01-14 01:19 UTC, 1ng-HeberH approved these changes, later dismissed
Nice work Cosme

2021-01-14 17:16 UTC, LeyaimMagma requested changes

2021-01-14 17:16 UTC, LeyaimMagma commented on tribomobile/App.js
> +        <Text style={{marginLeft:35, marginBottom:10, marginTop:10}}>{titlesText.titleRegistrationFormasPago}</Text>
x2

2021-01-15 20:40 UTC, 1ng-HeberH approved these changes, later dismissed
Niceeeeeee!

2021-01-18 18:43 UTC, 1ng-HeberH approved these changes, later dismissed

2021-01-18 18:55 UTC, 1ng-HeberH approved these changes
good job cosme!!

2021-01-18 18:56 UTC, JordiGN approved these changes
Cool design, it looks pretty much like the one in the design document! Great job!

2021-01-18 19:09 UTC, LeyaimMagma approved these changes

2021-01-18 19:14 UTC, luisarmandodv approved these changes

2021-01-18 19:14 UTC, merged